0830 Algorithm 2
f-lab-edu/problem-solve-refactoring pull request #3
Opened 2024-08-30 08:25 UTC by kw0n0

문제 번호: 17070번
문제 유형 : 그래프 & DP
풀이 방법 : DFS와 DP 활용하여 풀이

2024-09-01 11:20 UTC, f-lab-jake requested changes
lodash 사용하고 전체적으로 개선해보세요.

2024-09-02 00:24 UTC, kw0n0 commented
> lodash 사용하고 전체적으로 개선해보세요.

lodash 사용 시 장/단점을 개인적으로 정리해봤습니다. 제가 놓치고 있는 부분이 있을까요?

장점
    1. 제공되는 함수를 조합해 복잡한 데이터 조작을 간결하고 직관적으로 작성가능하다.
    2. 다양한 util 함수를 제공하고 코드의 일관성 유지에도 도움을 준다.
    3. 충분히 테스트되고 검증된 함수들로 안정적인 결과를 제공한다.

단점
    1. 간단한 작업이라면 약간의 성능저하가 있을 수 있다.
    2. 익숙하지 않은 개발자들은 함수와 패턴을 학습하는데 시간이 소요된다.
    3. 번들크기가 증가하여 로딩시간이 증가할 수 있다.(필요한 함수만 사용해서 최적화 가능한 부분)

2024-09-02 14:08 UTC, f-lab-jake commented
다음 멘토링에 자세히 얘기해봅시다.

2024-09-06 07:07 UTC, kw0n0 commented on boj/17070.ts
> +  .filter(([i, j]) => graph[j][i] === 1);
@f-lab-jake 
조금 더 생각을 해봤는데, 이중 for문을 통해 필요한 배열만 생성하는 것이 성능적으로는 좀 더 유리해보입니다.
- 이중 for문: 순회하면서 필요한 요소만 생성
- 현재 코드 : 우선 생성해두고 filter를 적용

 여기서부터는 이제 성능에 중점을 둘지 or 좀 더 파악이 쉬운 코드를 작성할지 선택하는 영역이 되는걸까요?

2024-09-06 14:49 UTC, f-lab-jake approved these changes

2024-09-06 14:49 UTC, f-lab-jake commented on boj/17070.ts
> +  .filter(([i, j]) => graph[j][i] === 1);
네 잘 분석했습니다.
1. 성능은 나은데 표현이 별로인 코드
2. 성능은 떨어지는데 표현이 좋은 코드
이때 2를 성능을 1과 똑같이 만들 방법이 많은경우에 존재합니다. 손쉽게 1로 되돌아가기보단 그 방법을 찾아봐야합니다. 이경우도 개선할방법이 있고 그건 나중에 배워봅시다.

2024-09-09 05:40 UTC, merged