feat: 10808
f-lab-edu/problem-solve-refactoring pull request #6
Opened 2024-09-06 01:46 UTC by kw0n0

문제 번호: 10808번
풀이 방법 : Map 자료구조를 활용해 풀이

2024-09-06 14:52 UTC, f-lab-jake requested changes

2024-09-06 14:52 UTC, f-lab-jake commented on boj/10808.ts
> +  }
`has`와 `get`을 동시에 쓰지마세요

2024-09-09 05:38 UTC, kw0n0 commented on boj/10808.ts
> +  }
@f-lab-jake 'get만 사용해도 요소의 존재여부를 판단할 수 있으니 활용하자'라는 의미로 받아들이고 수정해봤는데 제가 올바로 이해한게 맞을까요?

2024-09-10 01:52 UTC, f-lab-jake requested changes

2024-09-10 01:52 UTC, f-lab-jake commented on boj/10808.ts
>    }
이제 마저 중복을 제거해봅시다.

2024-09-18 04:12 UTC, merged